#!/bin/sh

[ -e debian/tests.home ] || mkdir debian/tests.home
trap "rm -rf debian/tests.home" EXIT
export HOME="$(pwd)/debian/tests.home"

xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
